server:
  port: 8089

spring:
  application:
    name: controle-gastos

  data:
    mongodb:
      uri: mongodb://localhost:27017/controle-gastos
      database: controle-gastos

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework: INFO
    com.br.financaspessoais: DEBUG
