server:
  port: 8089

spring:
  application:
    name: controle-gastos

  data:
    mongodb:
      uri: ${MONGO_URI_NUVEM}
      database: controle-gastos

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: minha-chave-super-secreta-e-segura-minha-chave-super-secreta-e-segura
  expiration: 86400000

logging:
  level:
    org.springframework: INFO
    com.br.financaspessoais: DEBUG

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
